// api.ts: the studio's conveniences for a project's video.tsx or stills.tsx, in one import: `#studio`. A scene may import
// anything else in a feature's studio/ or models/ folder too, as `#lib/<area>/<feature>/<role>/<file>`.

export { BrandLogo, brandLogoFor, type StudioBrand, type StudioBrandLogo } from '#lib/picture/brand/studio/brand.tsx';
export { Blockout, type BlockoutShape, type BlockoutSubject } from '#lib/footage/previs/studio/blockout.tsx';
export { dollyMove, orbitMove, pushInMove, type BlockoutMove, type BlockoutPose } from '#lib/footage/previs/studio/blockout-camera.ts';
export { FlatBlockout, type FlatPiece, type FlatPieceKind, type FlatViewMoves } from '#lib/footage/previs/studio/flat-blockout.tsx';
export type { FlatKey, FlatPose, FlatView } from '#lib/footage/previs/studio/flat-blockout-pose.ts';
export { beatGrid, steadyBeatGrid, type BeatGrid } from '#lib/timing/timeline/models/beat-grid.ts';
export { assertKeysInOrder, camAt, camFit, camTop, camWhole, clampCam, lerpCam, pagePoint, rectToScreen, scaleFor, screenPoint, screenRect, view, viewOf, viewOfScreenRect, viewScale, type Cam, type Shot, type View } from '#lib/picture/camera/models/camera.ts';
export { applyAffine, centerOf, inflate, multiplyAffine, union, type AffineMatrix, type Point, type Rect } from '#lib/picture/frame/models/geometry.ts';
export { Capture, CaptureMotion, CaptureStates, CaptureSwap } from '#lib/footage/capture/studio/capture.tsx';
export { areStudioFontsLoaded, loadStudioFaces, useStudioFontsReady, whenStudioFontsLoaded, type StudioFontFile } from '#lib/picture/type/studio/fonts.ts';
export { ARCHIVO_FACE, DISPLAY_FONT, MONO_ADVANCE_EM, MONO_CAP_EM, MONO_FONT, type StudioFace } from '#lib/picture/type/models/faces.ts';
export { DEFAULT_VIDEO_FORMAT, fullFrameRect, type FrameSize, type VideoFormat } from '#lib/picture/frame/models/frame.ts';
export { FONT } from '#lib/picture/type/models/faces.ts';
export { captionFreeRect, captionSafeArea, pillCaptionBand, type CaptionBand, type CaptionBandRule } from '#lib/picture/captions/models/caption-band.ts';
export { READABLE_CAPTION_RULE, type CaptionPagingRule } from '#lib/picture/captions/models/caption-pages.ts';
export { useCaptionSafeArea, type CaptionRenderProps, type CaptionStyle } from '#lib/picture/captions/studio/caption-style.tsx';
export { CaptionKeycap, pillCaptions } from '#lib/picture/captions/studio/pill-captions.tsx';
export { wordPopCaptionBand, wordPopCaptions } from '#lib/picture/captions/studio/word-pop-captions.tsx';
export { FilmGrain, Vignette } from '#lib/picture/film/studio/grade.tsx';
export { ClickToBlur, ConfirmDialog, DrawPath, EndCard, GlassCard, MotionTitle, NativeMenu, ODOMETER_DIGIT_EM, Odometer, Phone, SPLIT_LABEL_STRIP, SectionCard, SplitCompare, WordReveal, phoneView, splitLeftRect, splitRightRect, wordRevealFinish, type OdometerMode, type OdometerProps, type SplitSide, type WordRevealTiming } from '#lib/picture/kit/studio/kit.tsx';
export { backOutEase, clamp, lerp, motionCurves, motionDurations, off, on, perceptualSpring, powerOutEase, seg, sineInOutEase, stagger, staggerFinish, type CurveRoles, type EaseFn, type PerceptualSpring, type StaggerFrom, type StaggerTiming } from '#lib/picture/motion/models/motion.ts';
export { ShutterBlur } from '#lib/picture/film/studio/motion-blur.tsx';
export { REEL_SHUTTER, shutterOpensAt, shutterTravel, smearSigma } from '#lib/picture/motion/models/shutter.ts';
export { motionAttrs, motionEchoAttrs, pieceMotionAttrs, unmeasuredAttrs, useMotionTag, type MotionTag } from '#lib/picture/measurement/studio/motion-tag.ts';
export { ClickRipple, ClipToBox, Cursor, CursorPath, Glass, Highlight, Spotlight, Tag, TakeCursor, Text, Wash, cursorAt, offscreen, type CursorKey } from '#lib/picture/kit/studio/overlays.tsx';
export { hashRandom, randomSeedFromKey, seededRandom } from '#lib/picture/motion/models/random.ts';
// The reel pieces: the high-energy register of music-led videos (skills/video-motion/references/reel-pieces.md).
// Each model is re-exported by name: the helpers it exports only for its own drawing stay out of the barrel.
export { BounceBall, FieldSwell, type BounceCallout } from '#lib/picture/reel/studio/bounce.tsx';
export { bouncingBallAt, type BallLaunch, type BallPhase, type BallPose, type BounceParams, type BounceTiming } from '#lib/picture/reel/models/bounce.ts';
export { fieldSwellAt, type FieldSwellOptions, type SwellFrom, type SwellPose } from '#lib/picture/reel/models/bounce-swell.ts';
export { CapturePlane, type CapturePlaneProps } from '#lib/picture/reel/studio/capture-plane.tsx';
export { PLANE_REST_POSE, capturePlaneProjection, capturePlaneView, lerpPlanePose, planeLiftStart, type CapturePlaneProjection, type PlaneLift, type PlanePose } from '#lib/picture/reel/models/capture-plane.ts';
export { ColumnField, type ColumnFieldProps } from '#lib/picture/reel/studio/column-field.tsx';
export { columnDiscCells, columnFieldHeight, columnFieldPoint, columnNoise, type ColumnBall, type ColumnBallState, type ColumnCameraMove, type ColumnCameraPose, type ColumnCameraState, type ColumnCell, type ColumnFieldLights, type ColumnFieldSpec, type ColumnLabel, type ColumnLight, type ColumnRise } from '#lib/picture/reel/models/column-field.ts';
export { columnBallAt, columnCameraAt, columnFieldProject, topDownPose } from '#lib/picture/reel/models/column-field-motion.ts';
export { columnTitaniumMaterial } from '#lib/picture/reel/studio/column-field-materials.ts';
export { FieldFlash, GlyphField, ShockRing } from '#lib/picture/reel/studio/glyph-field.tsx';
export { GLYPH_FIELD_COLORS, GLYPH_SHAPES, glyphFieldLayout, glyphPunchScale, glyphRegroupPlan, glyphWaveArrivals, type GlyphCell, type GlyphClip, type GlyphFieldSlot, type GlyphFilterStep, type GlyphFilterTiming, type GlyphFront, type GlyphHit, type GlyphImplode, type GlyphKey, type GlyphLayout, type GlyphPunch, type GlyphRegroup, type GlyphShape, type GlyphShapeKey, type GlyphWave } from '#lib/picture/reel/models/glyph-field.ts';
export { glyphFieldFrame, parseGlyphColor, type GlyphDraw, type GlyphFieldFrame, type GlyphFieldProps, type GlyphRest, type GlyphSample } from '#lib/picture/reel/models/glyph-field-frame.ts';
export { ReelHud, type ReelHudProps } from '#lib/picture/reel/studio/hud.tsx';
export { REEL_HUD_BOOT_DECODE, REEL_HUD_GLYPHS, REEL_HUD_PALETTE, REEL_HUD_SLOTS, REEL_HUD_SWAP_DECODE, reelHudBoxPoints, reelHudBoxes, reelHudDecode, reelHudGrounds, reelHudLitSquare, reelHudPlateMix, reelHudReadGrounds, reelHudTimecode, reelHudToneOver, reelHudToneWeights, type ReelHudCell, type ReelHudDecodeSchedule, type ReelHudGround, type ReelHudLayoutProps, type ReelHudPalette, type ReelHudRead, type ReelHudSection, type ReelHudSlot, type ReelHudTone } from '#lib/picture/reel/models/hud.ts';
export { LensFringe, channelSplitPrimitives } from '#lib/picture/reel/studio/lens.tsx';
export { lensFringeAt, lensFringeSubpixelMax, type LensFringeState, type LensFringeTiming } from '#lib/picture/reel/models/lens.ts';
export { Needle, type NeedleProps } from '#lib/picture/reel/studio/needle.tsx';
export { needleContactAt, needleCoversAt, needleExposuresAt, needleLensHeight, needlePoseAt, needleRig, needleScreenPoint, needleShotAt, type NeedleLensing, type NeedlePose, type NeedleRig, type NeedleRigSettings, type NeedleShot, type NeedleStrike, type NeedleTake } from '#lib/picture/reel/models/needle.ts';
export { FadeToBlack, GlitchFlash, RecapGrid, Shake, type RecapTile, type RecapTileView } from '#lib/picture/reel/studio/recap.tsx';
export { recapGridRects, recapPopStarts, recapTileUnder, shakeOffset, type GlitchHit, type GlitchLook, type RecapExit, type RecapLayout, type RecapOrder } from '#lib/picture/reel/models/recap.ts';
export { TickerBand, TickerBands, type TickerBandProps, type TickerBandsProps } from '#lib/picture/reel/studio/ticker.tsx';
export { layoutTickerRow, mixGlyphPose, tickerBreathAt, type GlyphPose, type TickerBreath, type TickerPose, type TickerRowStyle, type TickerSlot } from '#lib/picture/reel/models/ticker-layout.ts';
export { ARCHIVO_BASELINE_EM, ARCHIVO_CAP_EM, archivoAdvance, archivoKern, layoutGlyphLine, type GlyphAxes, type GlyphLine, type GlyphLineSlot, type VariableFontMetrics } from '#lib/picture/type/models/glyph-layout.ts';
export { TICKER_BOLD, TICKER_HERO_POSES, TICKER_LIGHT, TICKER_LOOKS, tickerLookBeat, type TickerColors, type TickerEnter, type TickerExit, type TickerHeroPoses, type TickerKick, type TickerLook } from '#lib/picture/reel/models/ticker.ts';
export { IndexLabel, RiseWord, SelectionBox, WeightWord, type WordSelection } from '#lib/picture/reel/studio/type.tsx';
export { SlantWord } from '#lib/picture/reel/studio/type-slant.tsx';
export { ScrambleText } from '#lib/picture/reel/studio/type-scramble.tsx';
export { CODE_GLYPHS, scrambleAt, scrambleFinish, slantMatrix, slantWordPose, type ScrambleTiming, type SlantEntrance, type SlantPose, type Tittle } from '#lib/picture/reel/models/type.ts';
export { useScene } from '#lib/picture/video/studio/scene.tsx';
export { useVideoFormat } from '#lib/picture/frame/studio/video-format.ts';
export { useScreenRect } from '#lib/picture/measurement/studio/screen-rect.ts';
export { defineVideo, videoFormatOf, type ScenePrevis, type VideoSound } from '#lib/picture/video/studio/video.ts';
export type { LineSpan, SceneClock } from '#lib/timing/timeline/models/video-layout.ts';
export { sceneCueSeconds, sceneForTimelineClock } from '#lib/picture/video/studio/timeline-scene.tsx';
export type { SceneRung } from '#lib/timing/timeline/models/scene-rung.ts';
export { blockingScene } from '#lib/footage/previs/studio/blocking-scene.tsx';
export { SFX, Sfx, SfxCueListAudio, SfxCueListPlaying, type SfxCueSound, type SfxSound } from '#lib/timing/sound/studio/sfx.tsx';
export { STILL_FEED_SIZES, STILL_PRESETS, type StillFitReport, type StillPreset } from '#lib/picture/stills/models/still-presets.ts';
export { CoverImage, FitText, STILL_CARD_TILT, StillCard, StillHud, defineStills, stillDesign, useStillFrame, type StillAxes, type StillCardTilt, type StillDesign, type StillFocus, type StillImage, type StillsDef } from '#lib/picture/stills/studio/stills.tsx';
export { checkSourcePins, fitTake, onTake, pinnedSourceTime, sceneTimeOf, takeFrameAt, takeMouseAt, takeShot, takeTimeAt, type Take, type TakeFit, type TakeFrame, type TakeMark, type TakeMouse } from '#lib/footage/capture/studio/take.ts';
export { ThreeStage, softboxEnvironment, type ThreeBloom, type ThreeEnvironment, type ThreeFrame, type ThreeLens, type ThreeSample } from '#lib/picture/film/studio/three-stage.tsx';
export { addVec3, crossVec3, dotVec3, lengthVec3, lerpVec3, scaleVec3, subVec3, unitVec3, type Vec3 } from '#lib/picture/frame/models/vec3.ts';
// Stamp painting: a recipe of opaque and glaze groups of passes of deposits, painted on the GPU with a private style's
// brushes (docs/private-styles.md, skills/video-canvas/SKILL.md).
export { compileStampPaintRecipe, stampPaintRecipe, type CompiledStampPaint, type PaintMaterial, type StampBloomSettings, type StampFillSettings, type StampGroupOptions, type StampGroupScope, type StampLiftSettings, type StampMaskSettings, type StampKeyedMaterial, type StampPaintColor, type StampPaintMaterial, type StampPaintPaper, type StampPaintRecipe, type StampPaintScope, type StampPassOptions, type StampPassScope, type StampSoftenSettings, type StampUnmaskSettings, type StampWashOptions, type StampWashScope, type StampWashWait, type StampWaterSettings } from '#lib/picture/stamp-paint/models/stamp-paint-recipe.ts';
export { visibleStampCountAt } from '#lib/picture/stamp-paint/models/stamp-deposit-reveal.ts';
export { stampRegionOutline, stampSmoothRegion, type StampFillApplication } from '#lib/picture/stamp-paint/models/stamp-fill.ts';
export { STAMP_FILL_PATTERNS, stampFillMarks, stampFillStrokePath, type StampFillGuides, type StampFillMark, type StampFillPattern, type StampFillStrokes, type StampFillTurns } from '#lib/picture/stamp-paint/models/stamp-fill-strokes.ts';
export { stampFittedEllipse, stampRoundedForm, type StampFormEllipse, type StampFormLight, type StampRoundedForm, type StampRoundedFormSettings } from '#lib/picture/stamp-paint/models/stamp-form.ts';
export type { StampEdge, StampPoint, StampRegion } from '#lib/picture/stamp-paint/models/stamp-region.ts';
export type { StampPaintField } from '#lib/picture/stamp-paint/models/stamp-paint-field.ts';
export type { StampGroupBoil, StampGroupMotion, StampGroupPaper } from '#lib/picture/stamp-paint/models/stamp-group-motion.ts';
export type { StampMaterialKeys } from '#lib/picture/stamp-paint/models/stamp-material-keys.ts';
export type { StampStrokePoint, StampPlacement } from '#lib/picture/stamp-paint/models/stamp-placement.ts';
export { STAMP_PRESSURE_PROFILES, type StampPressureCurve, type StampPressureProfileName, type StampStrokeHand } from '#lib/picture/stamp-paint/models/stamp-stroke-hand.ts';
export type { StampBlend, StampBrush, StampBrushMedia } from '#lib/picture/stamp-paint/models/stamp-brush.ts';
export type { ResolvedStampPaintStyle } from '#lib/picture/stamp-styles/models/style.ts';
// Pigment paint: a style that paints in pigment names its medium and pigments; a deposit lays a colour or a mixture.
export { PAINT_MEDIA, TITANIUM_WHITE, type PaintMedium } from '#lib/picture/paint/models/paint-medium.ts';
export type { PaintMixture, PaintMixturePart } from '#lib/picture/paint/models/paint-mixture.ts';
export type { PaintPigmentAppearance } from '#lib/picture/paint/models/paint-pigment.ts';
export { WATERCOLOUR_PIGMENTS } from '#lib/picture/paint/models/paint-watercolour-pigments.ts';
export { stampPaintStyle } from '#lib/picture/stamp-styles/studio/stamp-paint-styles.ts';
export { StampPainting } from '#lib/picture/stamp-styles/studio/stamp-painting.tsx';
