/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStudioRouteImport } from './routes/api.studio'
import { Route as MediaProjectRouteImport } from './routes/media.$project'
import { Route as ReviewStillsProjectRouteImport } from './routes/review-stills.$project'
import { Route as ProjectsProjectIndexRouteImport } from './routes/projects.$project.index'
import { Route as ProjectsProjectArtifactsSplatRouteImport } from './routes/projects.$project.artifacts.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioRoute = ApiStudioRouteImport.update({
  id: '/api/studio',
  path: '/api/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaProjectRoute = MediaProjectRouteImport.update({
  id: '/media/$project',
  path: '/media/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewStillsProjectRoute = ReviewStillsProjectRouteImport.update({
  id: '/review-stills/$project',
  path: '/review-stills/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIndexRoute = ProjectsProjectIndexRouteImport.update({
  id: '/projects/$project/',
  path: '/projects/$project/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectArtifactsSplatRoute =
  ProjectsProjectArtifactsSplatRouteImport.update({
    id: '/projects/$project/artifacts/$',
    path: '/projects/$project/artifacts/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/studio': typeof ApiStudioRoute
  '/media/$project': typeof MediaProjectRoute
  '/review-stills/$project': typeof ReviewStillsProjectRoute
  '/projects/$project/': typeof ProjectsProjectIndexRoute
  '/projects/$project/artifacts/$': typeof ProjectsProjectArtifactsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/studio': typeof ApiStudioRoute
  '/media/$project': typeof MediaProjectRoute
  '/review-stills/$project': typeof ReviewStillsProjectRoute
  '/projects/$project': typeof ProjectsProjectIndexRoute
  '/projects/$project/artifacts/$': typeof ProjectsProjectArtifactsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/studio': typeof ApiStudioRoute
  '/media/$project': typeof MediaProjectRoute
  '/review-stills/$project': typeof ReviewStillsProjectRoute
  '/projects/$project/': typeof ProjectsProjectIndexRoute
  '/projects/$project/artifacts/$': typeof ProjectsProjectArtifactsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/studio'
    | '/media/$project'
    | '/review-stills/$project'
    | '/projects/$project/'
    | '/projects/$project/artifacts/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/studio'
    | '/media/$project'
    | '/review-stills/$project'
    | '/projects/$project'
    | '/projects/$project/artifacts/$'
  id:
    | '__root__'
    | '/'
    | '/api/studio'
    | '/media/$project'
    | '/review-stills/$project'
    | '/projects/$project/'
    | '/projects/$project/artifacts/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStudioRoute: typeof ApiStudioRoute
  MediaProjectRoute: typeof MediaProjectRoute
  ReviewStillsProjectRoute: typeof ReviewStillsProjectRoute
  ProjectsProjectIndexRoute: typeof ProjectsProjectIndexRoute
  ProjectsProjectArtifactsSplatRoute: typeof ProjectsProjectArtifactsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio': {
      id: '/api/studio'
      path: '/api/studio'
      fullPath: '/api/studio'
      preLoaderRoute: typeof ApiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$project': {
      id: '/media/$project'
      path: '/media/$project'
      fullPath: '/media/$project'
      preLoaderRoute: typeof MediaProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-stills/$project': {
      id: '/review-stills/$project'
      path: '/review-stills/$project'
      fullPath: '/review-stills/$project'
      preLoaderRoute: typeof ReviewStillsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/': {
      id: '/projects/$project/'
      path: '/projects/$project'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof ProjectsProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/artifacts/$': {
      id: '/projects/$project/artifacts/$'
      path: '/projects/$project/artifacts/$'
      fullPath: '/projects/$project/artifacts/$'
      preLoaderRoute: typeof ProjectsProjectArtifactsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStudioRoute: ApiStudioRoute,
  MediaProjectRoute: MediaProjectRoute,
  ReviewStillsProjectRoute: ReviewStillsProjectRoute,
  ProjectsProjectIndexRoute: ProjectsProjectIndexRoute,
  ProjectsProjectArtifactsSplatRoute: ProjectsProjectArtifactsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
