// api.ts: the studio's conveniences for a project's video.tsx or stills.tsx, in one import: `#studio`. A scene may import
// anything else in lib/studio too, as `#studio/<folder>/<file>`.

export { BrandLogo, brandLogoFor, type StudioBrand, type StudioBrandLogo } from './brand/brand.tsx';
export * from './previs/blockout.tsx';
export * from './previs/blockout-camera.ts';
export { FlatBlockout, type FlatPiece, type FlatPieceKind, type FlatViewMoves } from './previs/flat-blockout.tsx';
export type { FlatKey, FlatPose, FlatView } from './previs/flat-blockout-pose.ts';
export * from '../models/timeline/beat-grid.ts';
export * from '#models/camera/camera.ts';
export * from './capture/capture.tsx';
export * from './fonts/fonts.ts';
export * from '#models/type/faces.ts';
export * from '#models/frame/frame.ts';
export * from './film/grade.tsx';
export * from './kit/kit.tsx';
export * from '#models/motion/motion.ts';
export * from './film/motion-blur.tsx';
export * from '#models/motion/shutter.ts';
export { motionAttrs, motionEchoAttrs, pieceMotionAttrs, unmeasuredAttrs, useMotionTag, type MotionTag } from './probe/motion-tag.ts';
export * from './kit/overlays.tsx';
export * from '#models/motion/random.ts';
// The reel pieces: the high-energy register of music-led videos (skills/video-motion/references/reel-pieces.md).
// Each model is re-exported by name: the helpers it exports only for its own drawing stay out of the barrel.
export * from './reel/bounce.tsx';
export { type BallLaunch, type BallPhase, type BallPose, type BounceParams, type BounceTiming, bouncingBallAt } from '#models/reel/bounce.ts';
export { fieldSwellAt, type FieldSwellOptions, type SwellFrom, type SwellPose } from '#models/reel/bounce-swell.ts';
export * from './reel/capture-plane.tsx';
export { type CapturePlaneProjection, capturePlaneProjection, capturePlaneView, lerpPlanePose, PLANE_REST_POSE, type PlaneLift, planeLiftStart, type PlanePose } from '#models/reel/capture-plane.ts';
export * from './reel/column-field.tsx';
export { type ColumnBall, type ColumnBallState, type ColumnCameraMove, type ColumnCameraPose, type ColumnCameraState, type ColumnCell, columnDiscCells, columnFieldHeight, type ColumnFieldLights, columnFieldPoint, type ColumnFieldSpec, type ColumnLabel, type ColumnLight, columnNoise, type ColumnRise } from '#models/reel/column-field.ts';
export { columnBallAt, columnCameraAt, columnFieldProject, topDownPose } from '#models/reel/column-field-motion.ts';
export { columnTitaniumMaterial } from './reel/column-field-materials.ts';
export * from './reel/glyph-field.tsx';
export * from '#models/reel/glyph-field.ts';
export * from '#models/reel/glyph-field-frame.ts';
export * from './reel/hud.tsx';
export { REEL_HUD_BOOT_DECODE, REEL_HUD_GLYPHS, REEL_HUD_PALETTE, REEL_HUD_SLOTS, REEL_HUD_SWAP_DECODE, reelHudBoxes, reelHudBoxPoints, type ReelHudCell, reelHudDecode, type ReelHudDecodeSchedule, type ReelHudGround, reelHudGrounds, type ReelHudLayoutProps, reelHudLitSquare, type ReelHudPalette, reelHudPlateMix, type ReelHudRead, reelHudReadGrounds, type ReelHudSection, type ReelHudSlot, reelHudTimecode, type ReelHudTone, reelHudToneOver, reelHudToneWeights } from '#models/reel/hud.ts';
export * from './reel/lens.tsx';
export * from '#models/reel/lens.ts';
export * from './reel/needle.tsx';
export { NEEDLE_RIG, needleContactAt, needleCoversAt, needleExposuresAt, needleLensHeight, type NeedleLensing, type NeedlePose, needlePoseAt, type NeedleRig, needleScreenPoint, type NeedleShot, needleShotAt, type NeedleStrike, type NeedleTake } from '#models/reel/needle.ts';
export * from './reel/recap.tsx';
export { type GlitchHit, type GlitchLook, type RecapExit, recapGridRects, type RecapLayout, type RecapOrder, recapPopStarts, recapTileUnder, shakeOffset } from '#models/reel/recap.ts';
export * from './reel/ticker.tsx';
export * from '#models/reel/ticker-layout.ts';
export { TICKER_BOLD, TICKER_HERO_POSES, TICKER_LIGHT, TICKER_LOOKS, type TickerColors, type TickerEnter, type TickerExit, type TickerHeroPoses, type TickerKick, type TickerLook, tickerLookBeat } from '#models/reel/ticker.ts';
export * from './reel/type.tsx';
export * from './reel/type-slant.tsx';
export * from './reel/type-scramble.tsx';
export { CODE_GLYPHS, scrambleAt, scrambleFinish, type ScrambleTiming, type SlantEntrance, slantMatrix, type SlantPose, slantWordPose, type Tittle } from '#models/reel/type.ts';
export { useScene } from './composition/scene.tsx';
export { useScreenRect } from './probe/screen-rect.ts';
export { defineScene, defineVideo, type LineSpan, type SceneClock, type ScenePrevis, type VideoSound } from './composition/timeline.ts';
export { sceneCueSeconds, sceneForTimelineClock } from './composition/timeline-scene.tsx';
export type { SceneRung } from '#models/timeline/scene-rung.ts';
export { BoardFrame, type BoardMove } from './ladder/board-frame.tsx';
export { blockingScene, boardFrameScene, titleCardScene } from './ladder/ladder-scenes.tsx';
export { TitleCard, type TitleCardCue } from './ladder/title-card.tsx';
export * from './sfx/sfx.tsx';
export { STILL_FEED_SIZES, STILL_PRESETS, type StillFitReport, type StillPreset } from '#models/still/still-presets.ts';
export { CoverImage, defineStills, FitText, STILL_CARD_TILT, StillCard, StillHud, stillDesign, useStillFrame, type StillAxes, type StillCardTilt, type StillDesign, type StillFocus, type StillImage, type StillsDef } from './stills/stills.tsx';
export * from './capture/take.ts';
export * from './film/three-stage.tsx';
export * from '#models/camera/vec3.ts';
