// api.ts: the studio's conveniences for a project's video.tsx or stills.tsx, in one import. A scene may import anything else too.

export { BrandLogo, brandLogoFor, type StudioBrand, type StudioBrandLogo } from './brand.tsx';
export * from './blockout.tsx';
export * from './blockout-camera.ts';
export * from '../models/timeline/beat-grid.ts';
export * from '#models/camera/camera.ts';
export * from './capture.tsx';
export * from './fonts.ts';
export * from '#models/type/faces.ts';
export * from '#models/frame/frame.ts';
export * from './grade.tsx';
export * from './kit.tsx';
export * from '#models/motion/motion.ts';
export * from './motion-blur.tsx';
export * from '#models/motion/shutter.ts';
export { motionAttrs, motionEchoAttrs, pieceMotionAttrs, unmeasuredAttrs, useMotionTag, type MotionTag } from './motion-tag.ts';
export * from './overlays.tsx';
export * from '#models/motion/random.ts';
// The reel pieces: the high-energy register of music-led videos (skills/video-motion/references/reel-pieces.md).
export * from './reel/bounce.tsx';
export * from './reel/capture-plane.tsx';
export * from './reel/column-field.tsx';
export * from './reel/glyph-field.tsx';
export * from './reel/hud.tsx';
export * from './reel/lens.tsx';
export * from './reel/needle.tsx';
export * from './reel/recap.tsx';
export * from './reel/ticker.tsx';
export * from '#models/reel/ticker-layout.ts';
export * from './reel/type.tsx';
export { useScene } from './scene.tsx';
export { useScreenRect } from './screen-rect.ts';
export { defineScene, defineVideo, type LineSpan, type SceneClock, type ScenePrevis, type VideoSound } from './timeline.ts';
export { sceneCueSeconds, sceneForTimelineClock } from './music-led/timeline-scene.tsx';
export * from './sfx.tsx';
export { STILL_FEED_SIZES, STILL_PRESETS, type StillFitReport, type StillPreset } from '#models/still/still-presets.ts';
export { CoverImage, defineStills, FitText, STILL_CARD_TILT, StillCard, StillHud, stillDesign, useStillFrame, type StillAxes, type StillCardTilt, type StillDesign, type StillFocus, type StillImage, type StillsDef } from './stills.tsx';
export * from './take.ts';
export * from './three-stage.tsx';
export * from '#models/camera/vec3.ts';
